# Generated by Django 4.0 on 2022-01-15 14:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("18c71b0f-2695-49ef-9b10-78e543633231"), primary_key=True, serialize=False
            ),
        ),
    ]
