# Generated by Django 4.0 on 2022-01-29 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9e762c96-8e13-4c12-a915-e1dad68fb96d'), primary_key=True, serialize=False),
        ),
    ]
