# Generated by Django 4.0 on 2022-01-29 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e3d80498-6acb-4f1a-82ec-99be71bcf486'), primary_key=True, serialize=False),
        ),
    ]
