# Generated by Django 4.0 on 2022-01-29 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('48b3fd3a-cd68-4d41-9eb1-95875040e410'), primary_key=True, serialize=False),
        ),
    ]
