# Generated by Django 4.0 on 2022-01-29 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cbd2de3f-7cc2-4fbd-a05e-3fb10e836e7b'), primary_key=True, serialize=False),
        ),
    ]
