# Generated by Django 3.2.12 on 2022-02-26 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddfba225-4a79-444a-81d4-86b26c9dd78d'), primary_key=True, serialize=False),
        ),
    ]
