# Generated by Django 3.2.12 on 2022-02-26 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.TextField(default=uuid.UUID('ab79fadc-a428-4c2c-8741-0e8c4e6254b9'), primary_key=True, serialize=False),
        ),
    ]
