# Generated by Django 4.0 on 2021-12-31 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('60acfdd8-651e-4f4c-bf5d-2da84cfb2cde'), primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthyear', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
