# Generated by Django 4.0 on 2022-01-15 14:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("bbf1524d-8d1c-4a88-8f34-1c858ee849cf"), primary_key=True, serialize=False
            ),
        ),
    ]
