# Generated by Django 4.0 on 2022-01-15 14:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b5305a99-cc2d-43f1-9561-ee4e8ba2fb38"), primary_key=True, serialize=False
            ),
        ),
    ]
