# Generated by Django 4.0 on 2022-01-29 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e088af7f-0906-4f14-a42e-901d6349012e'), primary_key=True, serialize=False),
        ),
    ]
