# Generated by Django 4.0 on 2022-01-29 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('18fc15a5-08aa-4e79-9cf3-62dc4e88410e'), primary_key=True, serialize=False),
        ),
    ]
