# Generated by Django 4.0 on 2022-02-05 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_staff_user_is_superuser_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('77799581-4f9e-4e17-88e5-16fd60ef643c'), primary_key=True, serialize=False),
        ),
    ]
